package-lock.json, package.json, src/components/Button/Button.tsx, src/screens/auth/LandingScreen.tsx, src/store/client/createAuthSlice.ts, src/store/client/createCounterSlice.ts, src/store/client/useStore.ts
- `main` <- `feature/zustand`
- Zustand 환경 셋팅
- zustand 라이브러리 추가
- Slice Pattern의 Zustand Store 셋팅 ([공식 문서](https://github.com/pmndrs/zustand/blob/main/docs/guides/slices-pattern.md))
- createOOOSlice 모듈, useStore 커스텀 훅으로 분리
- zustand 는 client state 관리 목적으로 도입하였기 때문에 `store/client` 디렉터리에서 관리하면 좋을 것 같습니다!
- slice pattern 예제 작성을 위해 임시로 createAuthSlice, createCounterSlice 모듈을 작성하였습니다. 추후에 제거하여도 좋습니다.
- Zustand slice pattern 사용시, `useStore` import 만으로 각 slice 모듈에서 관리하는 state 과 action 을 활용할 수 있습니다. (LandingScreen 참고)
- 추가로, Zustand middleware 설정도 지원하고 있는데, 현재 단계에서는 필요성을 느끼지 못해 셋팅하지 않았습니다!
- Zustand Middleware는 상태 변화를 추적하여 로깅, 디버깅, 비동기 작업, 상태 조작 등을 처리하는데 사용됩니다. ([공식문서](https://github.com/pmndrs/zustand#middleware))
- Close #6
=> ✨ feat: Zustand useStore hook 셋팅

ios/HealthMatchingProject.xcodeproj/project.pbxproj, ios/HealthMatchingProject/AppDelegate.mm, ios/HealthMatchingProject/HealthMatchingProject.entitlements, ios/HealthMatchingProject/Info.plist, ios/Podfile.lock, package-lock.json, package.json, src/App.tsx, src/lib/AppleHealthKit.ts, src/screens/auth/LandingScreen.tsx, src/screens/record/RecordsTabScreen.tsx
- `main` <- `feature/healthkit`
- Apple Health Kit Module 사용을 위한 React Native Health 패키지 및 관련 코드를 추가합니다.([공식문서](https://github.com/agencyenterprise/react-native-health))
- 해당 패키지 사용을 위한 lib 코드를 추가합니다.
- 유저의 Apple Health Kit 데이터가 업데이트 된 경우, 백엔드에게 알리기 위해 Background Observers 기능을 추가합니다.
- App내에서 AppleHealthKit에 접근 하기 전, 유저에게 접근권한을 받아오기 위해 App 실행 전 initHealthKit을 실행하는 코드가 추가되었습니다.
- 예시코드를 확인하기 위해, `LandingScreen.tsx` 접근이 되도록 로그인 버튼 disabled 속성을 수정하였습니다.
- Close #3
=> 📝 chore: react-native-health 패키지 및 lib 코드 추가

babel.config.js
- `main` <- `feature/fix_flatlist_error`
- @react-navigation/material-top-tabs을 사용하고있는 RecordsScreen.tsx, MatchScreen.tsx 진입 시 아래와 같은 에러가 발생합니다.
- [관련 공식 이슈 코멘트](https://github.com/facebook/react-native/issues/36828)를 참고하여, 해당 에러 방지를 위해 특정 babel plugin을 사용하지 않도록 config에서 제거합니다.
- 현재 제거된 babel plugin들은 웹 storybook 미사용으로 인해 사용되지 않을 예정입니다.
- Close #37
=> 🐛 fix: Flatlist error 방지를 위한 미사용 babel plugin 제거

src/navigators/MatchNavigator.tsx, src/screens/match/detail/MatchDetailProfileScreen.tsx, src/screens/match/detail/matching/MatchDetailMatchingMoreScreen.tsx, src/screens/match/detail/matching/MatchDetailMatchingScreen.tsx
- `main` <- `feature/matching-navigate`
- 매칭 상세 > 매칭탭 > ApplyListItem 클릭시, 프로필 navigate 후, 빈화면이 뜨는 이슈를 해결하였습니다.
- Close #71
=> 🐛 fix: 매칭 상세 매칭탭 프로필 navigate 이슈 해결

src/assets/styles/emotion.d.ts, src/assets/styles/theme.ts, src/components/Alarm/AlarmItem.tsx, src/components/Button/NavigateButton.tsx, src/components/Tag/Tag.tsx, src/components/Text/Text.tsx
- `main` <- `feature/type-refactor`
- 기존에 작성되어 있던 theme type을 `상수 타입 활용` 방식으로 변경하였습니다.
- 타입 변수명을 수정하였습니다.
- Close #80
=> 🔨 refactor: theme type 선언 수정

src/features/match/components/CreateMatchInformation/CreateMatchInformationItem.tsx, src/features/match/components/CreateMatchProfile/CreateMatchProfileSection.tsx, src/features/match/components/CreateMatchProfile/MatchInformationSection.tsx, src/features/match/components/MatchDetailProfile/MatchDetailMembers.tsx, src/features/match/components/MatchDetailProfile/MatchDetailProfileSection.tsx, src/features/match/components/MatchRadio/MatchCreateRadio.tsx, src/features/match/hooks/field/usePostField.ts, src/features/match/types/detail.ts, src/features/match/types/userField.ts, src/screens/match/create/CreateMatchInformationScreen.tsx, src/screens/match/create/CreateMatchProfileScreen.tsx, src/screens/match/detail/MatchDetailProfileScreen.tsx, src/screens/match/detail/MatchDetailScreen.tsx
- `main` <- `feature/create-field-api`
| 정보 입력 | 프로필 입력 | 매칭 생성 후 상세 페이지 이동 |
|--------|--------|--------|
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-09-08 at 17 54 19](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/0633aebb-0bf1-4204-97c7-5a9fea9023f1) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-09-08 at 17 54 54](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/420f0acc-d8d4-4bcf-b585-8294df4cdc2d) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-09-08 at 17 55 02](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/a35a2c80-e442-4fa0-b174-cc05813085c0) |
- 매칭 생성 API (POST /field)를 연동하였습니다. (formData 방식)
- 매칭 생성 성공 후, callBack 로직을 작성하였습니다.
- Close #85
=> ✨ feat: 매칭 생성 API 연동 및 상세 페이지 연동

src/lib/axios.ts
- `main` <- `feature/axios-array-param`
- axios 배열 파라미터 복수키 포맷을 변경합니다. (`url?key[]=value1&key[]=value2` -> `url?key=value1&key=value2`)
- 현재 백엔드에서 `ModelAttribute` 어노테이션을 활용하여 파라미터를 받고 있는데, 배열 포맷의 파라미터를 처리하려면 하드코딩으로 이어짐. 따라서 프론트에서 복수키 포맷 변경
- null, undefined 값은 제외시킴
- Close #94
=> ✨ feat: axios 배열 파라미터 복수키 포맷 변경 

src/features/match/components/MatchFilter/MatchFieldTypeFilterRadio.tsx, src/features/match/hooks/field/index.ts, src/features/match/hooks/field/keys.ts, src/features/match/hooks/field/useGetFieldCount.ts, src/features/match/hooks/field/useGetInfiniteFieldList.ts, src/features/match/types/field.ts, src/navigators/MatchNavigator.tsx, src/screens/match/list/MatchListScreen.tsx
- `main` <- `feature/match-list-refactor`
- 매칭 리스트 무한스크롤 관련 API 변동에 따른 응답값을 수정하였습니다.
- API 응답값 변경에 따라 `useInfiniteQuery` 에서 다음 데이터를 불러오는 로직이 간단해졌습니다. 마지막으로 불러와진 매칭 데이터의 `id` 값을 넘겨주는 방식으로 변경되었습니다. 존재하지 않는다면 `undefined` 를 리턴하며 마칩니다.
```js
getNextPageParam: lastPage => {
const {fieldsInfos} = lastPage;
return fieldsInfos.length === 0
? undefined
: fieldsInfos[fieldsInfos.length - 1].id;
},
```
- Close #101
=> 🔨 refactor: 매칭 리스트 - API 변동에 따른 응답값 수정

ios/Podfile.lock, package-lock.json, package.json, src/features/match/components/MatchDetailMatching/MatchApplyHeader.tsx, src/features/match/components/MatchDetailMatching/MatchApplyList.tsx, src/features/match/components/MatchDetailMatching/MatchApplyListItem.tsx, src/features/match/components/MatchDetailMatching/index.ts, src/features/match/hooks/fieldEntry/index.ts, src/features/match/hooks/fieldEntry/keys.ts, src/features/match/hooks/fieldEntry/useDeleteFieldEntry.ts, src/features/match/hooks/fieldEntry/useGetInfiniteFieldEntryBattleDetail.ts, src/navigators/MatchNavigator.tsx, src/screens/match/detail/MatchDetailScreen.tsx, src/screens/match/detail/matching/MatchDetailMatchingMoreScreen.tsx, src/screens/match/detail/matching/MatchDetailMatchingScreen.tsx
- `main` <- `feature/detail-matching`
- 매칭 상세 매칭탭에 대한 feature 컴포넌트를 리팩토링 하고, API 연동 작업을 진행하였습니다.
| 매칭탭 목록 | 신청한 매칭 상세 | 신청한 매칭 상세 설정모드 | 신청 취소 선택 후 모달 | 
|--------|--------|--------|--------|
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-09-26 at 17 02 17](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/ad033638-543a-4a61-a1a4-656d7c8cab91) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-09-26 at 17 02 24](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/2298b49d-d644-441d-9b04-996e0658a179) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-09-26 at 17 02 27](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/dfad3d37-f75a-465a-b7ee-31658da598c1) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-09-26 at 17 02 …
=> ✨ feat: 매칭 상세 매칭탭 - API 연동

src/features/match/hooks/fieldEntry/index.ts, src/features/match/hooks/fieldEntry/usePostFieldEntryBattle.ts, src/features/match/hooks/fieldEntry/usePostFieldEntryTeam.ts, src/screens/match/detail/MatchDetailProfileScreen.tsx, src/screens/match/detail/MatchDetailScreen.tsx, src/utils/types.ts
- `main` <- `feature/match-apply`
- 매칭 상세 프로필 탭에서 매칭 신청 및 팀원 신청 API 연동하였습니다.
| 팀원 신청 성공 | 팀원 신청 오류 (서버 메시지 수정될 예정) | 매칭 신청 화면 | 팀원 신청 화면 |
|--------|--------|--------|--------|
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-10-06 at 22 25 04](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/803ecbed-f6b7-432a-86eb-fd544f3067de) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-10-05 at 22 49 51](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/0052af17-d509-4106-9a44-d719c713c52e) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-10-05 at 22 46 59](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/fcbc17b7-eae4-439b-94ad-c8b108cff9a2) |  ![Simulator Screen Shot - iPhone 14 Pro - 2023-10-05 at 22 47 …
=> ✨ feat: 매칭 상세 프로필탭 - 매칭 신청 및 팀원 신청 API 연동

src/features/home/components/MatchPreviewSection/MatchPreviewSection.tsx, src/features/home/components/MatchPreviewSection/MatchingBar.tsx, src/features/home/components/MatchPreviewSection/MatchingPreviewDuelBattleSection.tsx, src/features/home/components/MatchPreviewSection/MatchingPreviewDuelSection.tsx, src/features/home/components/MatchPreviewSection/MatchingPreviewSectionCard/MatchingPreviewSectionCard.tsx, src/features/home/components/MatchPreviewSection/MatchingPreviewSectionCard/MatchingPreviewSectionCardListItem.tsx, src/features/home/components/MatchPreviewSection/MatchingPreviewSectionCard/index.ts, src/features/home/components/MatchPreviewSection/MatchingPreviewTeamBattleSection.tsx, src/features/home/components/MatchPreviewSection/MatchingPreviewTeamSection.tsx, src/features/home/components/MatchPreviewSection/NoMatching.tsx, src/features/home/components/MatchPreviewSection/ProfileName.tsx, src/features/home/components/MatchPreviewSection/Tab/Tab.tsx, src/features/home/components/MatchPreviewSection/Tab/TabContent.tsx, src/features/home/components/MatchPreviewSection/Tab/index.ts, src/features/home/components/MatchPreviewSection/index.ts, src/features/home/components/index.ts, src/features/home/hooks/userField/index.ts, src/features/home/hooks/userField/keys.ts, src/features/home/hooks/userField/useGetUserFieldHomeBattle.ts, src/features/home/hooks/userField/useGetUserFieldHomeTeam.ts, src/features/home/types/index.ts, src/features/home/types/userField.ts, src/screens/home/HomeScreen.tsx
- `main` <- `feature/home_matching_preview`
- 홈(메인)스크린 내 '매칭 탭' 요약 보기 기능을 구현합니다.
|진행 중인 매칭 없는 경우(공통)|1:1 매칭| 팀 매칭 | 매칭안함 |
|:---:|:---:|:---:|:---:|
|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/3d391e5b-f161-4d5c-b08d-1e909a513a04)|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/b4954a54-58fe-4ec8-b36d-024f5dec5244)|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/929b38bf-9d8b-4a97-9a9c-802d363b2690)|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/50926224-f846-4a77-835d-2a242dc29efb)| 
|(모두 목업데이터 예시입니다)|
- `ScrollView` 내 `TopTabNavigator` 사용 불가로 인해, `Animated` 기능으로 Tab UI를 구현하였습니다. ([관련 이슈](https://github.com/react-navigation/react-navigation/issues/11067)) …
=> ✨ feat: 홈(메인)스크린 내 '매칭 탭' 요약 보기 기능 구현

src/features/auth/hooks/auth/usePostLogin.ts, src/features/home/components/MatchPreviewSection/MatchingPreviewTeamSection.tsx, src/features/home/hooks/userField/useGetUserFieldHomeTeam.ts, src/lib/toast.ts, src/navigators/AppNavigator.tsx, src/screens/auth/LandingScreen.tsx, src/screens/auth/LoginScreen.tsx
- `develop` <- `feature/login-screen`
- 일반 로그인 스크린을 추가합니다.
| 로그인 화면 | 로그인 화면 (서버 에러 메세지) | 
|:---:|:---:|
|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/ee9cbe7d-875a-49c3-a4e4-df8857476583)|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/5952dfa5-0980-4b63-a171-b50337406621)|
-  현재 사용하는 toast가 모두 유사한 스타일과 위치로 사용하는 것 같아, 기본 스타일 값을 제공하는 lib 코드를 추가하였습니다.
- Main 화면 진입 시, useGetUserFieldHomeTeam api 빈 스트링 처리가 되지 않아 타입 에러가 발생하여, 해당 처리를 추가하였습니다. ([관련 문의](https://www.notion.so/seonhye0113/Front-Back-e96f51ba9d734d4cbe1cc2aee02d7aa2?pvs=4))
- Close #100
=> ✨ feat: 일반 로그인 스크린 추가

src/features/match/components/MatchDetailMember/MatchExitButton.tsx, src/features/match/hooks/field/usePatchChangeLeader.ts, src/features/match/hooks/fieldEntry/usePostFieldEntryAccept.ts, src/features/match/hooks/userField/useDeleteUserFieldEject.ts, src/features/match/hooks/userField/useDeleteUserFieldExit.ts, src/screens/match/detail/matching/MatchDetailMatchingMoreScreen.tsx, src/screens/match/detail/member/MatchDetailMemberAssignScreen.tsx, src/screens/match/detail/member/MatchDetailMemberDeleteScreen.tsx, src/screens/match/detail/member/MatchDetailMemberRequestAcceptScreen.tsx
- `main` <- `feature/member-callback`
- 매칭 상세 팀원 탭에 대해 mutate 성공, 실패 상황에 대한 작업을 마쳤습니다. 
- 우선 서버에서 보내주는 에러 메시지를 활용하는 방식으로 진행하였습니다.
| useDeleteUserFieldExit | usePatchChangeLeader | useDeleteUserFieldEject |
|--------|--------|--------|
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-10-15 at 22 23 43](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/bddf40f5-9fc6-4e54-b7c4-448babaa9212) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-10-15 at 22 23 52](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/1ae47726-990f-4b96-a9d1-b873274c4f08) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-10-15 at 22 24 00](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/c7261866-f9c6-401f-92fb-3f5d09328f6e) | 
- 현재 기능 별로 mutate onSuccess, …
=> ✨ feat: 매칭 상세 팀원 탭 - mutate onSuccess, onError Callback 작업

src/features/home/components/MainBanner.tsx, src/features/notification/components/NotificationList.tsx, src/features/notification/components/NotificationListItem.tsx, src/features/notification/components/index.ts, src/features/notification/hooks/index.ts, src/features/notification/hooks/keys.ts, src/features/notification/hooks/useGetNotificationUser.ts, src/features/notification/hooks/usePatchNotificationUserRead.tsx, src/features/notification/types/index.ts, src/features/notification/types/notification.ts, src/navigators/BottomTabNavigator.tsx, src/navigators/HomeNavigator.tsx, src/navigators/index.ts, src/screens/home/HomeScreen.tsx, src/screens/home/NotificationScreen.tsx, src/screens/home/index.ts
- `main` <- `feature/user_notification2`
-  notification 컴포넌트 추가 및 Home 화면의 `NotificationScreen`을 추가합니다.
- notification(알림) 관련 feature component, hook, type을 추가합니다.
- Notification 스크린을 추가합니다.
-  [x] `HomeNavigator` 추가
-  [x] `HomeScreen`에서 `NotificationScreen` 네비게이트 추가
- 알림 무한스크롤로 많은 내역을 조회한 상태에서 뒤로가기 후 스크린 재진입 시, cache된 페이지 모두 한꺼번에 요청을 보내는 이슈가 있습니다. (ex. 20페이지 까지 조회 이후 재진입시, 초기 pageNumber 부터 시작하지 않고 한꺼번에 20번의 api가 보내지는 이슈)
- 위 이슈를 해결하기 위해 query에 `cacheTime: 0` 옵션이 추가되었습니다.
- Close #107
=> ✨ feat: notification 컴포넌트 추가 및 NotificationScreen 추가

src/features/auth/hooks/auth/index.ts, src/features/auth/hooks/auth/usePostRefreshAccessToken.ts, src/lib/axios.ts, src/navigators/AppNavigator.tsx, src/screens/auth/LandingScreen.tsx
- `main` <- `feature/refresh_token`
- Landing Screen 마운트 시, asyncStorage에 refreshToken 있을 경우, accessToken 재발급 및 재등록(자동 로그인) 기능을 추가합니다.
- 재발급 성공 시, MainScreen(Home)으로 이동 합니다.
- axios 401 에러 응답에 대한 에러 핸들링 코드를 추가합니다.
- 유효하지 않거나 지원하지 않는 JWT 토큰 -> 로그인 페이지로 이동
- 만료된 토큰일 경우 -> accessToken 재발급 및 재등록
- Landing Screen 마운트 시 기존 로그인 유저인 경우, 자동 로그인 기능 추가
- axios 401 에러 핸들링 추가
- Close #99
=> ✨ feat: 자동 로그인 및 401 에러 핸들링 기능 추가

src/components/Header/HeaderBackButton.tsx, src/components/Header/HeaderTitle.tsx, src/components/Header/index.ts, src/navigators/MatchNavigator.tsx
- `main` <- `feature/header-option`
- Stack Navigator option 을 활용하여 헤더 커스텀 작업을 진행하였습니다. 
| headerTitle 있는 경우 | headerTitle 없는 경우, headerRight 개별 세팅 |
|--------|--------|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-11-24 at 15 29 58](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/e62c985a-4612-4116-9f3d-e1c64dade6b8) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-11-24 at 15 29 35](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/3f28ecd6-a0e4-4060-9ad3-a99f612bd8f8) | 
- 매칭별 알림 화면 연동 작업은 #124 이슈로 분리하여 진행하겠습니다.
- `Stack.Navigator` 에서 기본적으로 옵션값을 세팅한 후, 개별 `Stack.Screen` option 을 커스텀하는 방식으로 진행하였습니다.
```js
screenOptions={{
headerBackTitleVisible: false,
headerShadowVisible: false,
headerTitle: () => <HeaderTitle />,
headerLeft: () => …
```
=> ✨ feat: Stack Navigator Header 커스텀 작업

src/features/match/components/MatchDetailMember/MatchMemberList.tsx, src/screens/match/detail/member/MatchDetailMemberMoreScreen.tsx, src/screens/match/detail/member/MatchDetailMemberRequestAcceptScreen.tsx
- `main` <- `fix/field-entry-team`
- 팀원 요청 목록 데이터가 목록에 노출 되지 않는 이슈 원인을 파악하고, 해결하였습니다.
- 해당 버그 픽스 머지 이후, #151 에서 RN FlatList 활용하는 방식으로 리팩토링 진행하겠습니다. 
- Close #92
=> 🐛 fix: useGetFieldEntryTeam 데이터 노출 이슈 해결

src/components/TopBar/TopBar.tsx, src/navigators/MyNavigator.tsx, src/screens/my/MyScreen.tsx, src/screens/my/TeamWorkRateInfo.tsx, src/screens/my/profile/MyProfileModifyScreen.tsx, src/screens/my/profile/MyProfileScreen.tsx, src/screens/my/setting/SettingConnectedAccount.tsx, src/screens/my/setting/SettingResignationScreen.tsx, src/screens/my/setting/SettingScreen.tsx
- `main` <- `feature/topbar2`
-  `TopBar` 컴포넌트 내에 뒤로가기 버튼 클릭 시, `navigation.goBack()`을 자체적으로 수행하도록 수정합니다.
- 불꽃 레벨 설명 스크린에서 해당 `TopBar` 컴포넌트를 사용하도록 수정합니다.
- Close #Issue-Number
=>  🐛 fix: TeamWorkRateInfo(불꽃 레벨 설명 스크린) TopBar 사용으로 변경

src/features/auth/components/findId/MobilePhoneSection/SendCodeSection.tsx, src/features/auth/components/findId/MobilePhoneSection/VerifySection.tsx, src/features/auth/components/findPassword/MobilePhoneSection/SendCodeSection.tsx, src/features/auth/components/findPassword/MobilePhoneSection/VerifySection.tsx, src/features/auth/components/signup/MobilePhoneSection/SendCodeSection.tsx, src/features/auth/components/signup/MobilePhoneSection/VerifySection.tsx
- `main` <- `fix/mobile-verification-keypad`
- 전화번호 인증, 인증번호 확인 스크린에서 키패드 type을 `number-pad`로 수정합니다.
- 인증번호 확인 스크린에서 키패드에서 메세지 내 숫자코드가 인식되도록 오기입된 `textContentType` 를 제거합니다.
- 유의 사항, 참고할 내용을 추가합니다
- fix #162
=> 🐛 fix: 전화번호 인증, 인증번호 확인 스크린 keyboard 수정

src/components/KeyboardHidePressArea/KeyboardHidePressArea.tsx, src/components/KeyboardHidePressArea/index.ts, src/screens/auth/FindIdScreen.tsx, src/screens/auth/FindPasswordScreen.tsx, src/screens/auth/LoginScreen.tsx, src/screens/auth/PhysicalInfoScreen.tsx, src/screens/auth/SignupScreen.tsx, src/screens/my/profile/MyProfileModifyScreen.tsx
- `main` <- `fix/keypad_area`
- Keypad가 열려있고, Keypad 외부 화면 터치 시 Keyboard가 닫기도록 수정합니다.
- `KeyboardHidePressArea`에서 사용된 `TouchableWithoutFeedback` 컴포넌트는 단일 children을 받을 수 있습니다.
- fix #160
=> 🐛 fix:  auth 및 profile 페이지 Keypad 외부 화면 터치 시 Keyboard가 닫기도록 수정

src/features/my/components/overview/TeamworkRateSection/TeamworkRateFlameGroup.tsx, src/features/my/components/overview/TeamworkRateSection/TeamworkRateSection.tsx, src/features/my/components/teamworkRate/TeamworkRateHistoryCard.tsx, src/features/my/components/teamworkRate/index.ts, src/features/my/hooks/teamworkRate/index.ts, src/features/my/hooks/teamworkRate/keys.ts, src/features/my/hooks/teamworkRate/useGetTeamworkRateHistory.ts, src/features/my/types/index.ts, src/features/my/types/teamworkRate.ts, src/navigators/MyNavigator.tsx, src/screens/my/index.ts, src/screens/my/teamworkRate/TeamworkRateHistory.tsx, src/screens/my/teamworkRate/TeamworkRateInfo.tsx, src/screens/my/teamworkRate/index.ts
- `main` <- `feature/my_teamwork_rate_history`
- 나의 불꽃 히스토리 조회 기능을 추가합니다.
|나의 불꽃 히스토리 스크린 - 데이터가 없을 경우 | 나의 불꽃 히스토리 스크린 - 데이터가 있을 경우|
|:---:|:---:|
|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/32cd1eae-cd47-414d-8384-613b37d6b87b)|![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/e2abd77f-64ab-46dc-9321-8777320e162b)|
- 유의 사항, 참고할 내용을 추가합니다
- Close #146
=> ✨ feat: 마이페이지 - 나의 불꽃 히스토리 조회 기능 
